FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY src ./src
COPY server ./server
COPY scripts ./scripts
COPY uploads ./uploads

EXPOSE 5000

CMD ["node", "server/server.js"]
