'use client';

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { usePublicDesigns } from '../../hooks/use-designs';
import { useProducts } from '../../hooks/use-products';
import { Button } from '../../components/ui/button';
import { Loader2, Palette, Sparkles, Image as ImageIcon, ArrowRight, X } from 'lucide-react';
import type { Design, Product } from '../../lib/supabase';

export default function CommunityGalleryPage() {
    const { data: designs, isLoading } = usePublicDesigns();
    const { data: products } = useProducts();
    const [selectedDesign, setSelectedDesign] = useState<Design | null>(null);

    return (
        <div className="min-h-screen bg-[hsl(var(--muted))]">
            {/* Hero Banner */}
            <section className="relative overflow-hidden bg-gradient-to-r from-[hsl(var(--primary))] to-[hsl(var(--accent))]">
                <div className="absolute inset-0 bg-black/20" />
                <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12 md:py-16">
                    <div className="flex items-center justify-between">
                        <div>
                            <h1 className="text-3xl md:text-5xl font-bold font-display text-white">
                                Community Gallery
                            </h1>
                            <p className="text-white/80 mt-2 text-sm md:text-base">
                                Discover and use stunning designs generated by our community.
                            </p>
                        </div>
                        <div className="hidden md:block">
                            <div className="bg-[hsl(var(--card))]/10 backdrop-blur-sm rounded-2xl p-4 border border-white/20">
                                <Palette className="h-12 w-12 text-white/90" />
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Designs Grid */}
            <section className="py-10 md:py-14">
                <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                    {isLoading ? (
                        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
                            {Array.from({ length: 10 }).map((_, i) => (
                                <div key={i} className="bg-[hsl(var(--card))] rounded-2xl overflow-hidden border border-[hsl(var(--border))] animate-pulse">
                                    <div className="aspect-square bg-[hsl(var(--muted))]" />
                                    <div className="p-3">
                                        <div className="h-4 bg-[hsl(var(--muted))] rounded w-3/4 mb-2" />
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : designs && designs.length > 0 ? (
                        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
                            {designs.map((design) => (
                                <div
                                    key={design.id}
                                    className="group bg-[hsl(var(--card))] rounded-xl overflow-hidden border border-[hsl(var(--border))] hover:shadow-xl hover:shadow-[hsl(var(--primary)/0.08)] transition-all duration-300 hover:-translate-y-1 cursor-pointer"
                                    onClick={() => setSelectedDesign(design)}
                                >
                                    <div className="aspect-square bg-[hsl(var(--muted))] relative overflow-hidden">
                                        {design.original_image_url ? (
                                            <Image
                                                src={design.original_image_url}
                                                alt={design.prompt}
                                                fill
                                                className="object-cover group-hover:scale-105 transition-transform duration-300"
                                                sizes="(max-width: 640px) 50vw, 25vw"
                                                unoptimized
                                            />
                                        ) : (
                                            <div className="flex items-center justify-center h-full">
                                                <ImageIcon className="h-12 w-12 text-[hsl(var(--muted-foreground)/0.3)]" />
                                            </div>
                                        )}
                                        {/* Overlay with prompt snippet */}
                                        <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-3 pt-8 translate-y-full group-hover:translate-y-0 transition-transform duration-300">
                                            <p className="text-xs text-white line-clamp-2 font-medium">
                                                "{design.prompt}"
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="text-center py-20 bg-[hsl(var(--card))] rounded-3xl border border-[hsl(var(--border))] shadow-sm">
                            <Sparkles className="h-12 w-12 text-[hsl(var(--muted-foreground)/0.3)] mx-auto mb-4" />
                            <h3 className="text-lg font-semibold mb-2">No public designs yet</h3>
                            <p className="text-[hsl(var(--muted-foreground))] mb-6 max-w-md mx-auto">
                                Be the first to generate an awesome design and share it with the community!
                            </p>
                            <Link href="/studio">
                                <Button variant="gradient" className="rounded-full">
                                    <Sparkles className="mr-2 h-4 w-4" /> Go to Studio
                                </Button>
                            </Link>
                        </div>
                    )}
                </div>
            </section>

            {/* Modal for Selected Design */}
            {selectedDesign && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
                    <div className="bg-[hsl(var(--card))] rounded-3xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col md:flex-row shadow-2xl relative">
                        <button
                            onClick={() => setSelectedDesign(null)}
                            className="absolute top-4 right-4 z-10 p-2 bg-black/20 hover:bg-black/40 text-white rounded-full transition"
                        >
                            <X className="h-5 w-5" />
                        </button>

                        {/* Left: Image */}
                        <div className="md:w-1/2 bg-[hsl(var(--muted))] relative min-h-[300px] md:min-h-0">
                            {selectedDesign.original_image_url && (
                                <Image
                                    src={selectedDesign.original_image_url}
                                    alt="Design"
                                    fill
                                    className="object-cover"
                                    unoptimized
                                />
                            )}
                        </div>

                        {/* Right: Info & Actions */}
                        <div className="md:w-1/2 p-6 md:p-8 flex flex-col h-[50vh] md:h-auto">
                            <h3 className="text-xl font-bold font-display mb-1">Community Design</h3>
                            <p className="text-[hsl(var(--muted-foreground))] text-sm italic mb-6">"{selectedDesign.prompt}"</p>

                            <h4 className="font-medium text-sm mb-3">Apply to a Product:</h4>

                            <div className="flex-1 overflow-y-auto pr-2 grid grid-cols-1 sm:grid-cols-2 gap-3 mb-6">
                                {products?.map((p: any) => (
                                    <Link
                                        key={p.id}
                                        href={`/gallery/${p.id}?design=${selectedDesign.id}`}
                                        className="flex items-center gap-3 p-3 rounded-xl border border-[hsl(var(--border))] hover:border-[hsl(var(--primary))] hover:bg-[hsl(var(--primary)/0.03)] transition group"
                                    >
                                        {p.image_url && (
                                            <div className="relative h-12 w-12 rounded-lg overflow-hidden bg-[hsl(var(--muted))] shrink-0">
                                                <Image src={p.image_url} alt={p.name} fill className="object-cover" sizes="48px" />
                                            </div>
                                        )}
                                        <div className="flex-1 min-w-0">
                                            <p className="text-sm font-semibold truncate group-hover:text-[hsl(var(--primary))] transition">{p.name}</p>
                                            <p className="text-[10px] text-[hsl(var(--muted-foreground))] uppercase tracking-wider">{p.category}</p>
                                        </div>
                                    </Link>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
